### ISSUE TITLE
I18n::ArgumentError Transliteration rule must be a proc or a hash.

### ISSUE THREAD

**Issue by ktopolski** [prograils/lit#155]
Hello,

First of all - thank you for this tool! It delivers a lot of value to our team and UX is good enough for non-tech people to use it - great job :).

Recently we hit the issue described in the title. I18n just refused to work and every page where the translations were invoked resulted in good ol' 500.

I didn't find other workaround than to do `Lit::LocalizationKey.where("localization_key LIKE 'i18n.transliterate%'").destroy_all`, but this one proves to be effective.

I have no explanation why the error happened and why Lit under `"i18n.transliterate.rule"` key contained the value of `"size cannot be greater than %{num}"`

Just to be clear: this issue is to let you know there might be a potential problem, the fix I mentioned above works for us for the time of writing.

- Lit version: `1.0.2`
- i18n version: `1.8.5`
- rails version: `5.2.4.4`

stack trace:

```
I18n::ArgumentError: Transliteration rule must be a proc or a hash.
  from i18n/backend/transliterator.rb:25:in `get'
  from i18n/backend/transliterator.rb:13:in `transliterate'
  from i18n.rb:289:in `transliterate'
  from active_storage/filename/parameters.rb:17:in `ascii'
  from active_storage/filename/parameters.rb:11:in `combined'
  from active_storage/filename/parameters.rb:27:in `to_s'
  from active_storage/service.rb:135:in `content_disposition_with'
  from active_storage/service/disk_service.rb:78:in `block in url'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from active_storage/service.rb:124:in `instrument'
  from active_storage/service/disk_service.rb:77:in `url'
  from active_storage/blob.rb:127:in `service_url'
  from active_storage/blobs_controller.rb:12:in `show'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:194:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from action_controller/metal/instrumentation.rb:34:in `block in process_action'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from action_controller/metal/instrumentation.rb:32:in `process_action'
  from action_controller/metal/params_wrapper.rb:256:in `process_action'
  from active_record/railties/controller_runtime.rb:24:in `process_action'
  from abstract_controller/base.rb:134:in `process'
  from action_view/rendering.rb:32:in `process'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:52:in `dispatch'
  from action_dispatch/routing/route_set.rb:34:in `serve'
  from action_dispatch/journey/router.rb:52:in `block in serve'
  from action_dispatch/journey/router.rb:35:in `each'
  from action_dispatch/journey/router.rb:35:in `serve'
  from action_dispatch/routing/route_set.rb:840:in `call'
```

Hope you'll find it useful :).

Cheers!

**Comment by mlitwiniuk** [comment]
@ktopolski There is `Lit.ignored_keys` setting, you can set it to `Lit.ignored_keys = ['i18n.transliterate']` to always ignore transliteration rules. In fact I'll add this as a default to generated initializer.

**Comment by mlitwiniuk** [comment]
Default initializer modified in #156
