### ISSUE TITLE
webpack without asset pipeline: `method_missing': undefined method `assets' for #<Rails::Application::Configuration

### ISSUE THREAD

**Issue by gingerlime** [prograils/lit#167]
Can lit work without the asset pipeline? our Rails app uses webpack and we removed the asset pipeline. Running `rails g lit:install` produces this error

```
...
        1: from /usr/local/bundle/gems/lit-1.1.1/lib/lit/engine.rb:10:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-6.0.3.6/lib/rails/railtie/configuration.rb:96:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x000056502c0f0d48> (NoMethodError)
```

**Comment by pnikrat** [comment]
I don't think we support webpack-only projects for now (maybe if we were able to finally get rid of some frontend dependencies like jquery etc.). Maybe there is a way to adjust the code for webpack-only projects but we are not able to investigate it now and in the near future. If  you have any ideas please submit the PR
