### ISSUE TITLE
:en is not a valid locale (I18n::InvalidLocale) upon initializing Lit

### ISSUE THREAD

**Issue by RandieM** [prograils/lit#171]
Hello.

I am having a problem with a fresh Rails 6.0.3.6 app, in which the only additional gem is Lit.

As soon as Lit is initialized, I get the error below.

If I add :en to the app's available locales, it makes the error go away, but this is not a good option for me, because my app will not be translated to English. This is what I currently have in my application.rb:

```
config.i18n.available_locales = %i[de fr it]
config.i18n.default_locale = :de
```

Any ideas?

Error:
```
I, [2021-04-20T16:03:10.963802 #12866]  INFO -- : initializing Lit
~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/i18n-1.8.10/lib/i18n.rb:343:in `enforce_available_locales!': :en is not a valid locale (I18n::InvalidLocale)
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/i18n-1.8.10/lib/i18n.rb:199:in `translate'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.6/lib/active_support/core_ext/array/conversions.rb:70:in `to_sentence'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/application/finisher.rb:36:in `block in <module:Finisher>'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `instance_exec'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `run'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:61:in `block in run_initializers'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `call'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
  from ~/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:60:in `run_initializers'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/application.rb:363:in `initialize!'
  from ~/path/to/bwo/config/environment.rb:7:in `<main>'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/application.rb:339:in `require_environment!'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/command/actions.rb:28:in `require_environment!'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/commands/generate/generate_command.rb:21:in `perform'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/command/base.rb:69:in `perform'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/command.rb:46:in `invoke'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.0.3.6/lib/rails/commands.rb:18:in `<main>'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  from bin/rails:4:in `<main>'
```

**Comment by mlitwiniuk** [comment]
@RandieM it seems like lit is calling something before rails manages to pass default values to I18n. Try creating initializer with following content:
```ruby
I18n.config.available_locales = %i[de fr it]
I18n.default_locale = :de
```

**Comment by RandieM** [comment]
@mlitwiniuk, thanks a lot for your quick response.

I followed your advice and the error seems to be gone.

Would this be the solution or a temporary work-around?

**Comment by RandieM** [comment]
That's strange, as mine was also a newly-created app. Thanks for the work-around, though.
